models/Post.php
<?php

namespace app\models;

use DateTime;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property int $user_id
 * @property string $status
 * @property string $title
 * @property string $website
 * @property string $body
 * @property string|null $media
 * @property string|null $hashtag
 * @property string $date_publication_start
 * @property string|null $date_publication_end
 * @property string $created_at
 * @property string $updated_at
 */
class Post extends \yii\db\ActiveRecord
{
	const FILE_PATH = 'images/posts/';
	
	const STATUS_ON = 'on';
	const STATUS_DRAFT = 'draft';
	
	public function isPublished(): bool
	{
		$publicationStartDate = new DateTime($this->date_publication_start);
		$now = new DateTime("now");
		
		return $publicationStartDate < $now;
	}
	
	public function getPath(): string
	{
		return !empty($this->media) ? '/' . self::FILE_PATH . $this->media : "";
	}
	
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'status', 'title', 'body', 'date_publication_start'], 'required'],
            [['date_publication_start', 'date_publication_end', 'created_at', 'updated_at'], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            [['user_id'], 'integer'],
            [['body'], 'string'],
            [['status'], 'string', 'max' => 10],
            [['title', 'website', 'media', 'hashtag'], 'string', 'max' => 250],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'status' => 'Status',
            'title' => 'Title',
            'body' => 'Body',
            'media' => 'Media',
            'hashtag' => 'Hashtag',
            'date_publication_start' => 'Date Publication Start',
            'date_publication_end' => 'Date Publication End',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
	
	public function getUser()
	{
		return $this->hasOne(User::className(), ['id' => 'user_id']);
	}
	
	public function getSocials() {
		return $this->hasMany(Socials::className(), ['id' => 'social_id'])
			->viaTable('posts_socials', ['post_id' => 'id']);
	}
	
	public static function statusList(): array
	{
		return [
			self::STATUS_DRAFT => 'DRAFT',
			self::STATUS_ON => 'ON',
		];
	}
	
	public static function findByUserAndSocial($userId, $socialId)
	{
		return self::find()
			->joinWith('socials')
			->where(['posts.user_id' => $userId])
			->andWhere(['socials.id' => $socialId])
			->all();
	}
	
	public function getSocialsArray(): array
	{
		$socialList = [];
		/** @var Socials $social */
		foreach ($this->getSocials()->all() as $social) {
			$socialList[$social->id] = $social->name;
		}
		
		return $socialList;
	}
	
	public function socialsCheckedArr(array $allSocials): array
	{
		$postsList = [];
		/** @var Socials $social */
		foreach ($this->getSocials()->all() as $social) {
			$postsList[$social->id] = $social->name;
		}
		
		foreach ($allSocials as $userSocial) {
			foreach ($postsList as $postSocial) {
			    if ($userSocial[0] === $postSocial[0]) {
					$userSocial['checked'] = true;
			    }
			}
		}
		
		return $allSocials;
	}
}

models/PostForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

class PostForm extends Model
{
	public $status;
	public $title;
	public $body;
	/**
	 * @var UploadedFile $mediaFile attribute
	 */
	public $mediaFile;
	public $media;
	public $hashtag;
	public $website;
	public $date_publication_start;
	public $socials;
	
	public function uploadMediaFile()
	{
		$this->mediaFile = UploadedFile::getInstance($this, 'mediaFile');
		if ($this->validate()) {
			if (!empty($this->mediaFile)) {
				$this->media = time() . $this->mediaFile->baseName . '.' . $this->mediaFile->extension;
				if (!is_dir(Post::FILE_PATH)) {
					mkdir(Post::FILE_PATH, 0777, true);
				}
				$this->mediaFile->saveAs(Post::FILE_PATH . $this->media);
			}
			return true;
		} else {
			var_dump($this->errors);
			return false;
		}
	}
	
	/**
	 * @return array the validation rules.
	 */
	public function rules()
	{
		return [
			[['status', 'title', 'date_publication_start', 'body', 'socials'], 'required'],
			[['date_publication_start',], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
			[['title', 'media', 'website', 'hashtag'], 'string', 'max' => 250],
			[['status'], 'string', 'max' => 10],
			[['mediaFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
			['socials', 'each', 'rule' => ['integer']],
			['socials', 'socialsValidator'],
		];
	}
	
	public function socialsValidator($attributeName, $params)
	{
		$isError = false;
		$user = UserModel::findOne(['id' => Yii::$app->user->id]);
		
		if (empty(array_diff($this->socials, Socials::userSocialsList($user->id)))) {
			$this->addError('socials', 'You have entered an unknown social network.');
			$isError = true;
		}
		
		if (!empty($user->getMembership()->one())) {
			$platformsCount = (int) $user->getMembership()->one()->platforms_count;
			if ($platformsCount !== -1) {
				if (count($this->socials) > $platformsCount) {
					$this->addError('socials', 'The number of selected social networks has been exceeded.');
					$isError = true;
				};
			}
		} else {
			$this->addError('socials', 'You need selected membership.');
			$isError = true;
		}
		
		return $isError;
	}
	
	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'socials' => 'Publish to',
			'mediaFile' => 'Add media',
		];
	}
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\PostForm;
use app\models\PostUpdateForm;
use app\models\PostUpdateMediaForm;
use app\models\Socials;
use app\models\UserModel;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\filters\AccessControl;
use yii\helpers\BaseHtml;
use yii\helpers\BaseStringHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'models' => $dataProvider->getModels(),
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
    	$model = $this->findModel($id);
    	
    	if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
    	}
    	
        return $this->render('view', [
            'model' => $model,
        ]);
    }
	
	public function actionViewJson($id)
	{
		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		
		$model = $this->findModel($id);
		
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
		
		$response = [];
		$response['id'] = $model->id;
		$response['title'] = $model->title;
		$response['body_short'] = BaseStringHelper::truncate($model->body, 50);
		$response['body'] = $model->body;
		$response['media'] = '/' . Post::FILE_PATH . $model->media;
		$response['hashtag'] = $model->hashtag;
		$response['website'] = $model->website;
		$response['date_publication_start'] = $model->date_publication_start;
		$response['is_published'] = $model->isPublished();
		
		return $this->asJson($response);
	}

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelForm = new PostForm();

        $posts = Yii::$app->request->post();
        if ($modelForm->load($posts) && $modelForm->validate()) {
			$user = UserModel::findOne(['id' => Yii::$app->getUser()->getId()]);
			if (!$user->isCanPublish()) {
				Yii::$app->session->setFlash('warning', 'You have run out of attempts to create growth.');
				return $this->redirect(['pricing-plans/index']);
			}
			
			if($modelForm->uploadMediaFile()) {
				$model = new Post();
				$model->user_id = Yii::$app->getUser()->getId();
				$model->created_at = date('Y-m-d H:m:s');
				$model->updated_at = date('Y-m-d H:m:s');
				$model->media = $modelForm->media;
				$model->status = $modelForm->status;
				$model->title = $modelForm->title;
				$model->body = $modelForm->body;
				$model->hashtag = $modelForm->hashtag;
				$model->date_publication_start = $modelForm->date_publication_start;
				if ($model->save()) {
					$user->publications_count = $user->publications_count - 1;
					$user->save();
					
					foreach ($modelForm->socials as $socialId) {
						$model->link('socials', Socials::findOne($socialId));
					}
					
					Yii::$app->session->setFlash('success', 'New post created successful.');
					return $this->redirect(['view', 'id' => $model->id]);
				} else {
					Yii::$app->session->setFlash('error', 'Error save new Post');
				}
			} else {
				Yii::$app->session->setFlash('error', 'Error upload media file for new post');
			}
        }
        
        return $this->render('create', [
            'model' => $modelForm,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		$modelForm = new PostUpdateForm();
		$modelForm->title = $model->title;
		$modelForm->status = $model->status;
		$modelForm->website = $model->website;
		$modelForm->body = $model->body;
		$modelForm->hashtag = $model->hashtag;
		$modelForm->date_publication_start = $model->date_publication_start;

		if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
			$model->title = $modelForm->title;
			$model->body = $modelForm->body;
			$model->website = $modelForm->website;
			$model->status = $modelForm->status;
			$model->hashtag = $modelForm->hashtag;
			$model->date_publication_start = $modelForm->date_publication_start;
			$model->updated_at = date('Y-m-d H:m:s');
			if ($model->save()) {
				$model->unlinkAll('socials', true);
				foreach ($modelForm->socials as $socialId) {
					$model->link('socials', Socials::findOne($socialId));
				}
				
				return $this->redirect(['view', 'id' => $model->id]);
			}
		}
	
		$postUpdateMediaForm = new PostUpdateMediaForm();
	
		return $this->render('update', [
			'model' => $model,
			'modelForm' => $modelForm,
			'postUpdateMediaForm' => $postUpdateMediaForm,
		]);
	}
    
    public function actionUpdateMediaFile($id)
    {
		$model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		$modelForm = new PostUpdateMediaForm();
		$posts = Yii::$app->request->post();
		if ($modelForm->load($posts)) {
			if (!empty($model->media)) {
				$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
				if (file_exists($pathToFile)) {
					unlink($pathToFile);
				}
				$model->media = null;
				$model->save();
			}
			if($modelForm->uploadMediaFile()) {
				$model->media = $modelForm->media;
				$model->updated_at = date('Y-m-d H:m:s');
				$model->save();
			}
		}
		
		return $this->redirect(['/post/update', 'id' => $model->id]);
    }

    public function actionDeleteMediaFile($id)
    {
		$model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		if(!empty($model->media)) {
			$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
			$model->media = null;
			$model->updated_at = date('Y-m-d H:m:s');
			if (!$model->save()) {
				var_dump($model->errors);
			}
		}
		
		return $this->redirect(['/post/update', 'id' => $model->id]);
    }
    
    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		if(!empty($model->media)) {
			$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
		}
		
		$model->delete();
		
        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/post/_form.php
<?php

use app\models\Post;
use kartik\datetime\DateTimePicker;
use kartik\file\FileInput;
use mihaildev\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostForm */
/* @var $form yii\widgets\ActiveForm */
?>
<script src="https://cdn.tiny.cloud/1/zxmp5lpicnhmeex0y9h60r7btfx12ooizxhra6jm4he1g3od/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
		<div class="col-lg-6">
			<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

			<?= $form->field($model, 'body')->textarea(['rows' => '6', 'id' => 'mytextarea']) ?>
			
			<div class="row">
				<div class="col-lg-6"><?= $form->field($model, 'hashtag')->textInput(['maxlength' => true]) ?></div>
				<div class="col-lg-6"><?= $form->field($model, 'website')->textInput(['maxlength' => true]) ?></div>
				<div class="col-lg-6"><?= $form->field($model, 'status')->dropDownList(Post::statusList()) ?></div>
				<div class="col-lg-6">
					<?= $form->field($model, 'date_publication_start', ['inputOptions' => [
						'autocomplete' => 'off']])->widget(DateTimePicker::class, [
						'name' => 'birthdate',
						'options' => ['placeholder' => 'Select date publication ...'],
						'convertFormat' => true,
						'pluginOptions' => [
							'format' => 'yyyy-MM-dd HH:mm:ss',
							'startDate' => date('Y-m-d H:i:s'),
							'todayHighlight' => true
						]
					]) ?>	
				</div>
			</div>
		</div>
	
		
		<div class="col-lg-6">
			<?= $form->field($model, 'mediaFile')->widget(FileInput::classname(), [
				'options' => [/*'multiple' => true,*/ 'accept' => 'image/*'],
			]); ?>
		</div>
	</div>
	
	<?php $socials = \app\models\Socials::userSocialsList(Yii::$app->user->id);
	if (empty($socials)) { ?>
		<div class="alert">You need to register in at least one social network.</div>
		<div class="form-group">
			<?= Html::submitButton('Save draft', ['class' => 'btn btn-lg btn-secondary', 'disabled' => true]) ?>
		</div>
	<?php }else{ ?>
		<div class="form-group social_check">
			<?php echo $form->field($model, 'socials[]')->checkboxList(\app\models\Socials::userSocialsList(Yii::$app->user->id)); ?>
		</div>
		<div class="btn-group">
			<?= Html::submitButton('Save draft', ['class' => 'btn btn-lg btn-primary', 'id' => 'save_post_btn']) ?>
		</div>
	<?php }; ?>

    <?php ActiveForm::end(); ?>

</div>
<script>
	document.addEventListener("DOMContentLoaded", function(event) {
		tinymce.init({
			selector: "#mytextarea",
			plugins: "emoticons",
			toolbar: "emoticons",
			toolbar_location: "bottom",
			menubar: false
		});

		let selectedValue = $('#postform-status').val();
		function statusPost(selectedValue){
			switch (selectedValue) {
				case 'on':
					$('#save_post_btn').text('Schedule');
					break;
				default:
					$('#save_post_btn').text('Save as draft');
					break;
			}
		};
		statusPost(selectedValue);
		$('#postform-status').on('change', function(){
			statusPost($(this).val());
		});
	});
</script>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'body') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

/**
 * @var $userSocials \app\models\Socials[]
 */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create page">

    <div class="page__wrapper py-5">
        <h1 class="page__title mb-5"><?= Html::encode($this->title) ?></h1>
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>

</div>

views/post/index.php
<?php

use yii\helpers\BaseStringHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $models \app\models\Post[] */

$this->title = 'Post list';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="page">
	<div class="page__wrapper py-5">
		<h4 class="page__subtitle">Post list</h4>
		<h2 class="page__title">Post list</h2>

		<div class="posts row">
			
			<?php foreach ($models as $model): ?>

				<div class="col-lg-4 col-md-6 post">
					<article class="post__item">
						<?php if (!empty($model->media)) { ?>
							<div class="post__preview">
								<a href="<?php echo Url::toRoute(['/post/view', 'id' => $model->id]); ?>"><img src="/<?php echo \app\models\Post::FILE_PATH . $model->media; ?>" alt="<?php echo $model->title; ?>"></a>
							</div>
						<?php }; ?>
						
						<div class="post__content">
							<h2 class="post__title"><a href="<?php echo Url::toRoute(['/post/view', 'id' => $model->id]); ?>"><?php echo $model->title; ?></a></h2>
							<div class="post_inner__publish">Publication date: <strong><?php echo $model->date_publication_start; ?></strong></div>
							<div class="post_inner__socials">
								Publicate to: 
								<?php
								/** @var \app\models\Socials $social */
								foreach ($model->getSocials()->all() as $social) {; ?>
									<strong><?php echo $social->name; ?></strong>
								<?php }; ?>
							</div>
							<div class="post__excerpt"><?php echo BaseStringHelper::truncate($model->body, 100); ?></div>
							<a class="post__link" href="<?php echo Url::toRoute(['/post/view', 'id' => $model->id]); ?>">Continue reading</a>
						</div>
					</article>
				</div>
			<?php endforeach; ?>
		</div>
<!--		<div class="pagination">-->
<!--			<ul class="pagination__list">-->
<!--				<li class="pagination__item"><a class="pagination__link" href="#">&#x276E;</a></li>-->
<!--				<li class="pagination__item"><a class="pagination__link" href="#">1</a></li>-->
<!--				<li class="pagination__item"><a class="pagination__link" href="#">2</a></li>-->
<!--				<li class="pagination__item"><a class="pagination__link" href="#">3</a></li>-->
<!--				<li class="pagination__item"><a class="pagination__link" href="#">&#x276F;</a></li>-->
<!--			</ul>-->
<!--		</div>-->
	</div>
</div>

views/post/update.php
<?php

use kartik\datetime\DateTimePicker;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $modelForm app\models\PostUpdateForm */
/* @var $postUpdateMediaForm app\models\PostUpdateMediaForm */

$this->title = 'Update Post: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<script src="https://cdn.tiny.cloud/1/zxmp5lpicnhmeex0y9h60r7btfx12ooizxhra6jm4he1g3od/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<div class="post-update page">

    <div class="page__wrapper py-5">
    	<h1 class="page__title mb-5"><?= Html::encode($this->title) ?></h1>
		
		<div class="post-form">
			<div class="row">
				<div class="col-lg-6">
					<?php $form = ActiveForm::begin(); ?>
					
					<?= $form->field($modelForm, 'title')->textInput(['maxlength' => true]) ?>
					
					<?= $form->field($modelForm, 'body')->textarea(['rows' => 6, 'id' => 'mytextarea']) ?>
		
					<div class="row">
						
						<div class="col-lg-6"><?= $form->field($modelForm, 'hashtag')->textInput(['maxlength' => true]) ?></div>
						
						<div class="col-lg-6"><?= $form->field($modelForm, 'website')->textInput(['maxlength' => true]) ?></div>
						
					</div>
					<div class="row">
						
						<div class="col-lg-6"><?= $form->field($modelForm, 'status')->dropDownList(\app\models\Post::statusList()) ?></div>
						
						<div class="col-lg-6">
							<?= $form->field($modelForm, 'date_publication_start', ['inputOptions' => [
								'autocomplete' => 'off']])->widget(DateTimePicker::class, [
								'name' => 'date_publication_start',
								'options' => ['placeholder' => 'Select date publication ...'],
								'convertFormat' => true,
								'pluginOptions' => [
									'format' => 'yyyy-MM-dd HH:mm:ss',
									'startDate' => date('Y-m-d H:i:s'),
									'todayHighlight' => true
								]
							]) ?>
						</div>
						
					</div>
					
					<?= $form->field($modelForm, 'socials[]')->checkboxList(\app\models\Socials::userSocialsList(Yii::$app->user->id), [
						'item' => function($index, $label, $name, $checked, $value) use ($model){
							$postSocialsArr = $model->getSocialsArray();
							if(array_key_exists($value, $postSocialsArr)){
								$checked = 'checked';
							}
							return Html::checkbox($name, $checked, [
								'value' => $value,
								'label' => $label,
							]);
						}
					]) ?>
			
					<div class="form-group">
						<?= Html::submitButton('Update', ['class' => 'btn btn-lg btn-primary', 'id' => 'save_post_btn']) ?>
					</div>
					
					<?php ActiveForm::end(); ?>
				</div>
	
				<div class="col-lg-6">
					<?php if (empty($model->media)) { ?>
						<?php $form2 = ActiveForm::begin(['action' => ['post/update-media-file', 'id' => $model->id], 'options' => ['method' => 'post', 'class' => 'file_upload__form']]); ?>
						
							<?= $form2->field($postUpdateMediaForm, 'mediaFile')->widget(FileInput::classname(), [
								'options' => ['accept' => 'image/*'],
							]); ?>
						<?php ActiveForm::end(); ?>
					<?php } else { ?>
						<div class="post_edit__image">
							<img src="<?php echo $model->getPath(); ?>" alt="<?php echo $model->title; ?>">
							<a href="<?php echo Url::toRoute(['/post/delete-media-file', 'id' => $model->id]); ?>" title="Delete" aria-label="Delete" data-pjax="0" data-confirm="Are you sure you want to delete this item?" class="btn btn-danger" data-method="post">Delete Media File</a>
						</div>
					<?php } ?>
				</div>
			</div>
		</div>

		
    </div>
</div>


<script>
	document.addEventListener("DOMContentLoaded", function(event) {
		tinymce.init({
			selector: "#mytextarea",
			plugins: "emoticons",
			toolbar: "emoticons",
			toolbar_location: "bottom",
			menubar: false
		});

		let selectedValue = $('#postupdateform-status').val();
		function statusPost(selectedValue){
			switch (selectedValue) {
				case 'on':
					$('#save_post_btn').text('Schedule');
					break;
				default:
					$('#save_post_btn').text('Save as draft');
					break;
			}
		};
		statusPost(selectedValue);
		$('#postupdateform-status').on('change', function(){
			statusPost($(this).val());
		});
	});
</script>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="post-view page">

	<div class="page__wrapper py-5">
   	
		<div class="post_inner">
			<div class="post_inner__content">
				<?php if (!empty($model->media)) { ?>
					<img src="<?php echo $model->getPath(); ?>" alt="<?php echo $model->title; ?>">
				<?php }; ?>
				<h2 class="post_inner__title"><?php echo $model->title; ?></h2>
				<div class="post_inner__staus">
					<div class="badge badge-pill badge-secondary">
						<?php
							if ($model->isPublished()) {
								echo '<span>This post has been published.</span>';
							} else {
								echo '<span>This post has not yet been published</span>';
							}
						?>
					</div>
				</div>
				<div class="post_inner__text"><?php echo $model->body; ?></div>
				<div class="post_inner__publish">Publication date: <strong><?php echo $model->date_publication_start; ?></strong></div>
				<?= $model->website ? '<p>Website ' . $model->website . ' </p>' : ''; ?>
				<!-- <p>Status <?= $model->status; ?></p> -->
				<div class="post_inner__socials">
					Publicate to: 
					<?php
					/** @var \app\models\Socials $social */
					foreach ($model->getSocials()->all() as $social) {; ?>
						<strong><?php echo $social->name; ?></strong>
					<?php }; ?>
				</div>

				<div class="post_inner__edit_post">
					<a href="<?php echo \yii\helpers\Url::toRoute(['/post/update', 'id' => $model->id]); ?>" class="btn btn-lg btn-primary">Edit post</a>
				</div>
			</div>
		</div>
	</div>

</div>