controllers/PostController.php
<?php

namespace app\controllers;

use app\models\PostForm;
use app\models\PostUpdateForm;
use app\models\PostUpdateMediaForm;
use app\models\Socials;
use app\models\UserModel;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\filters\AccessControl;
use yii\helpers\BaseHtml;
use yii\helpers\BaseStringHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'models' => $dataProvider->getModels(),
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
    	$model = $this->findModel($id);
    	
    	if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
    	}
    	
        return $this->render('view', [
            'model' => $model,
        ]);
    }
	
	public function actionViewJson($id)
	{
		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		
		$model = $this->findModel($id);
		
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
		
		$response = [];
		$response['id'] = $model->id;
		$response['title'] = $model->title;
		$response['body_short'] = BaseStringHelper::truncate($model->body, 50);
		$response['body'] = $model->body;
		$response['media'] = '/' . Post::FILE_PATH . $model->media;
		$response['hashtag'] = $model->hashtag;
		$response['website'] = $model->website;
		$response['date_publication_start'] = $model->date_publication_start;
		$response['is_published'] = $model->isPublished();
		
		return $this->asJson($response);
	}

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelForm = new PostForm();

        $posts = Yii::$app->request->post();
        if ($modelForm->load($posts) && $modelForm->validate()) {
			$user = UserModel::findOne(['id' => Yii::$app->getUser()->getId()]);
			if (!$user->isCanPublish()) {
				Yii::$app->session->setFlash('warning', 'You have run out of attempts to create growth.');
				return $this->redirect(['pricing-plans/index']);
			}
			
			if($modelForm->uploadMediaFile()) {
				$model = new Post();
				$model->user_id = Yii::$app->getUser()->getId();
				$model->created_at = date('Y-m-d H:m:s');
				$model->updated_at = date('Y-m-d H:m:s');
				$model->media = $modelForm->media;
				$model->status = $modelForm->status;
				$model->title = $modelForm->title;
				$model->body = $modelForm->body;
				$model->hashtag = $modelForm->hashtag;
				$model->date_publication_start = $modelForm->date_publication_start;
				if ($model->save()) {
					$user->publications_count = $user->publications_count - 1;
					$user->save();
					
					foreach ($modelForm->socials as $socialId) {
						$model->link('socials', Socials::findOne($socialId));
					}
					
					Yii::$app->session->setFlash('success', 'New post created successful.');
					return $this->redirect(['view', 'id' => $model->id]);
				} else {
					Yii::$app->session->setFlash('error', 'Error save new Post');
				}
			} else {
				Yii::$app->session->setFlash('error', 'Error upload media file for new post');
			}
        }
        
        return $this->render('create', [
            'model' => $modelForm,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		$modelForm = new PostUpdateForm();
		$modelForm->title = $model->title;
		$modelForm->status = $model->status;
		$modelForm->website = $model->website;
		$modelForm->body = $model->body;
		$modelForm->hashtag = $model->hashtag;
		$modelForm->date_publication_start = $model->date_publication_start;

		if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
			$model->title = $modelForm->title;
			$model->body = $modelForm->body;
			$model->website = $modelForm->website;
			$model->status = $modelForm->status;
			$model->hashtag = $modelForm->hashtag;
			$model->date_publication_start = $modelForm->date_publication_start;
			$model->updated_at = date('Y-m-d H:m:s');
			if ($model->save()) {
				$model->unlinkAll('socials', true);
				foreach ($modelForm->socials as $socialId) {
					$model->link('socials', Socials::findOne($socialId));
				}
				
				return $this->redirect(['view', 'id' => $model->id]);
			}
		}
	
		$postUpdateMediaForm = new PostUpdateMediaForm();
	
		return $this->render('update', [
			'model' => $model,
			'modelForm' => $modelForm,
			'postUpdateMediaForm' => $postUpdateMediaForm,
		]);
	}
    
    public function actionUpdateMediaFile($id)
    {
		$model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		$modelForm = new PostUpdateMediaForm();
		$posts = Yii::$app->request->post();
		if ($modelForm->load($posts)) {
			if (!empty($model->media)) {
				$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
				if (file_exists($pathToFile)) {
					unlink($pathToFile);
				}
				$model->media = null;
				$model->save();
			}
			if($modelForm->uploadMediaFile()) {
				$model->media = $modelForm->media;
				$model->updated_at = date('Y-m-d H:m:s');
				$model->save();
			}
		}
		
		return $this->redirect(['/post/update', 'id' => $model->id]);
    }

    public function actionDeleteMediaFile($id)
    {
		$model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		if(!empty($model->media)) {
			$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
			$model->media = null;
			$model->updated_at = date('Y-m-d H:m:s');
			if (!$model->save()) {
				var_dump($model->errors);
			}
		}
		
		return $this->redirect(['/post/update', 'id' => $model->id]);
    }
    
    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
	
		if ($model->user_id !== Yii::$app->getUser()->getId()) {
			throw new NotFoundHttpException('Post is not found');
		}
	
		if(!empty($model->media)) {
			$pathToFile = __DIR__ . '/../web/' . Post::FILE_PATH . $model->media;
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
		}
		
		$model->delete();
		
        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/base.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\BaseAsset;
use yii\helpers\Html;

BaseAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">

	<!-- Useful meta tags -->
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="robots" content="index, follow">
	<meta name="google" content="notranslate">
	<meta name="format-detection" content="telephone=no">
	<meta name="description" content="">
	
	<?php $this->registerCsrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\bootstrap\Alert;
use yii\helpers\Html;

\app\assets\MainAsset::register($this);

/** @var \app\models\UserModel $user */
$user = \app\models\UserModel::findOne(Yii::$app->user->identity->id);

$menuItems = [];
if (Yii::$app->getUser()->getId() === 1) {
	$menuItems[] = ['label' => 'Social', 'url' => '/social/index', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'social/index'];
	$menuItems[] = ['label' => 'Membership', 'url' => '/membership/index', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'membership/index'];
	$menuItems[] = ['label' => 'Help Messages', 'url' => '/help-messages/index', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'help-messages/index'];
}

if (Yii::$app->user->isGuest) {
	$menuItems[] = ['label' => 'Lending', 'url' => '/site/index', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'site/calendar'];
	$menuItems[] = ['label' => 'Signup', 'url' => '/site/signup', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'site/signup'];
	$menuItems[] = ['label' => 'Login', 'url' => '/site/login', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'site/login'];
} else {
	$menuItems[] = ['label' => 'Dashboard', 'url' => '/site/calendar', 'icon' => 'cera-icon cera-layout', 'isActive' =>  $this->context->route == 'site/calendar'];
	$menuItems[] = ['label' => 'Connected Socials', 'url' => '/user-social/index', 'icon' => 'cera-icon cera-heart', 'isActive' =>  $this->context->route == 'user-social/index'];
	$menuItems[] = ['label' => 'Upcoming Posts (List)', 'url' => '/post/index', 'icon' => 'cera-icon cera-list', 'isActive' =>  $this->context->route == 'post/index'];
	$menuItems[] = ['label' => 'Schedule New Post', 'url' => '/post/create', 'icon' => 'cera-icon cera-file', 'isActive' =>  $this->context->route == 'post/create'];
	$menuItems[] = ['html' => '<li class="sidebar__nav_item"><span class="sidebar__nav_item_devider"><span>Membership</span></span></li>'];
	$menuItems[] = ['label' => 'Pricing plans', 'url' => '/pricing-plans/index', 'icon' => 'cera-icon cera-dollar-sign', 'isActive' =>  $this->context->route == 'pricing-plans/index'];
	$menuItems[] = ['html' => '<li class="sidebar__nav_item"><span class="sidebar__nav_item_devider"><span>Others</span></span></li>'];
	$menuItems[] = ['label' => 'Help', 'url' => '/user-help-message/create', 'icon' => 'cera-icon cera-life-buoy', 'isActive' =>  $this->context->route == 'user-help-message/create'];
	$menuItems[] = ['label' => 'Log out', 'url' => '/site/logout', 'icon' => 'cera-icon cera-log-out', 'isActive' =>  $this->context->route == 'site/logout'];
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="robots" content="index, follow">
	<meta name="google" content="notranslate">
	<meta name="format-detection" content="telephone=no">
	<meta name="description" content="">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="site-container">
	<aside class="sidebar">
		<div class="sidebar__header">
			<div class="sidebar__logo">
				<a href="/post/create">New post <i class="fa fa-plus"></i></a>
			</div>
			<button type="button" class="btn btn-link">
				<i class="cera-icon cera-menu-arrow"></i>
			</button>
		</div>
		<nav class="sidebar__nav">
			<ul class="sidebar__nav_list">
				<?php foreach ($menuItems as $menuItem) { ?>
					<?php if (key_exists('html', $menuItem)) {
						echo $menuItem['html'];
					}else{; ?>
						<li class="sidebar__nav_item">
							<a class="sidebar__nav_item_link <?php echo !empty($menuItem['isActive']) ? 'active' : ''; ?>" href="<?php echo $menuItem['url']; ?>">
								<i class="<?php echo $menuItem['icon']; ?>"></i> <span><?php echo $menuItem['label']; ?></span>
							</a>
						</li>
					<?php }; ?>
				<?php }; ?>
			</ul>
		</nav>
	</aside>
	
	<main class="site-content">
		<header class="header">
			<div class="profile">
				<div class="profile__visible">
					<div class="profile__avatar">
						<img src="<?php echo !empty($user->photo) ? '/' . \app\models\UserModel::FILE_PHOTO . $user->photo : '/images/user-avatar.png'; ?>" alt="<?php echo $user->username; ?>">
					</div>
					<div class="profile__name"><?php echo $user->username; ?></div>
				</div>
				<div class="profile__dropdown">
					<ul class="profile__nav">
						<li class="profile__item"><a href="<?php echo \yii\helpers\Url::toRoute(['user/view']); ?>"><i class="cera-icon cera-user"></i> Profile</a></li>
						<li class="profile__item"><a href="<?php echo \yii\helpers\Url::toRoute(['user/update']); ?>"><i class="cera-icon cera-settings"></i> Settings</a></li>
						<li class="profile__item"><a href="<?php echo \yii\helpers\Url::toRoute(['site/logout']); ?>"><i class="cera-icon cera-log-out"></i> Log out</a></li>
					</ul>
				</div>
			</div>
		</header>

		<div class="content">
			<?= $content ?>
		</div>

		<footer class="">
			<div class="row d-flex flex-row justify-content-between align-items-center">
				<p class="m-0 col-md-6">Copyright © 2019 Cera. All rights reserved</p>
				<ul class="col-md-6">
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="#"><i class="fa fa-slack"></i></a></li>
				</ul>
			</div>
		</footer>
	</main>
</div>

<?php $this->endBody() ?>
<script>
	if($(window).width() < 768){
		$('.sidebar').addClass('closed')
	}
	$(window).resize(function(){
		if($(this).width() < 768){
			$('.sidebar').addClass('closed')
		}
	})
</script>
</body>
</html>
<?php $this->endPage() ?>