models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * Class User
 * @package app\models
 * @property Post[] $posts
 */

class User extends ActiveRecord implements IdentityInterface
{
	const STATUS_DELETED = 0;
	const STATUS_ACTIVE = 10;
	const STATUS_WAIT = 5;
	
	public function behaviors()
	{
		return [
//			TimestampBehavior::className(),
		];
	}
	
	public function rules()
	{
		return [
			['status', 'default', 'value' => self::STATUS_DELETED],
			['status', 'in', 'range' => [self::STATUS_DELETED, self::STATUS_WAIT, self::STATUS_ACTIVE]],
		];
	}
	
	public static function findIdentity($id)
	{
		return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
	}
	
	public static function findIdentityByAccessToken($token, $type = null)
	{
		throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
	}
	
	public static function findByUsername($username)
	{
		return static::findOne(['username' => $username]);
	}
	
	public static function findByPasswordResetToken($token)
	{
		
		if (!static::isPasswordResetTokenValid($token)) {
			return null;
		}
		
		return static::findOne([
			'password_reset_token' => $token,
			'status' => self::STATUS_ACTIVE,
		]);
	}
	
	public static function isPasswordResetTokenValid($token)
	{
		
		if (empty($token)) {
			return false;
		}
		
		$timestamp = (int) substr($token, strrpos($token, '_') + 1);
		$expire = Yii::$app->params['user.passwordResetTokenExpire'];
		return $timestamp + $expire >= time();
	}
	
	public function getId()
	{
		return $this->getPrimaryKey();
	}
	
	public function getAuthKey()
	{
		return $this->auth_key;
	}
	
	public function validateAuthKey($authKey)
	{
		return $this->getAuthKey() === $authKey;
	}
	
	public function validatePassword($password)
	{
		return Yii::$app->security->validatePassword($password, $this->password_hash);
	}
	
	public function setPassword($password)
	{
		$this->password_hash = Yii::$app->security->generatePasswordHash($password);
	}
	
	public function generateAuthKey()
	{
		$this->auth_key = Yii::$app->security->generateRandomString();
	}
	
	public function generatePasswordResetToken()
	{
		$this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
	}
	
	public function removePasswordResetToken()
	{
		$this->password_reset_token = null;
	}
	
	public static function findByEmail($email)
	{
		return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
	}
	
	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getPosts()
	{
		return $this->hasMany(Post::className(), ['user_id' => 'id']);
	}
	
	public function getSocials() {
		return $this->hasMany(Socials::className(), ['id' => 'social_id'])
			->viaTable('users_socials', ['user_id' => 'id']);
	}
	
	public function getMembership() {
		return $this->hasOne(Memberships::className(), ['id' => 'membership_id']);
	}
	
	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return 'users';
	}
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\ChangeEmailForm;
use app\models\LoadCoverForm;
use app\models\LoadPhotoForm;
use app\models\UserUpdateForm;
use app\services\ChangeEmailService;
use app\services\SignupService;
use Yii;
use app\models\UserModel;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for UserModel model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
	
	/**
	 * @return string
	 * @throws NotFoundHttpException
	 */
    public function actionView()
    {
        return $this->render('view', [
            'model' => $this->findModel(Yii::$app->getUser()->getId()),
        ]);
    }

    /**
     * Updates an existing UserModel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        $model = $this->findModel(Yii::$app->getUser()->getId());
  
		$modelForm = new UserUpdateForm();
		$modelForm->username = $model->username;
		$modelForm->first_name = $model->first_name;
		$modelForm->last_name = $model->last_name;
		$modelForm->birthdate = $model->birthdate;
		$modelForm->gender = $model->gender;
	
		if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
			$model->username = $modelForm->username;
			$model->first_name = $modelForm->first_name;
			$model->birthdate = $modelForm->birthdate;
			$model->last_name = $modelForm->last_name;
			$model->gender = $modelForm->gender;
			$model->updated_at = date('Y-m-d H:m:s');
			if (!empty($modelForm->newPassword)) {
				$model->password_hash = Yii::$app->security->generatePasswordHash($modelForm->newPassword);
			}
			if ($model->save()) {
				return $this->redirect(['view', 'id' => $model->id]);
			} else {
				var_dump($model->errors);
			}
		}
	
		$changeEmailForm = new ChangeEmailForm();
		$changeEmailForm->email = $model->new_email;
		
		return $this->render('update', [
			'model' => $model,
			'modelForm' => $modelForm,
			'loadPhotoModelForm' => new LoadPhotoForm(),
			'loadCoverModelForm' => new LoadCoverForm(),
			'changeEmailForm' => $changeEmailForm,
		]);
	}
	
	public function actionUpdatePhoto()
	{
		$model = $this->findModel(Yii::$app->getUser()->getId());
		
		$modelForm = new LoadPhotoForm();
		$photoPost = Yii::$app->request->post();
		if ($modelForm->load($photoPost)) {
			if (!empty($model->photo)) {
				$pathToFile = $model->getPhotoPath();
				if (file_exists($pathToFile)) {
					unlink($pathToFile);
				}
				$model->photo = null;
				$model->save();
			}
			if($modelForm->uploadMediaFile()) {
				$model->photo = $modelForm->photo;
				$model->updated_at = date('Y-m-d H:m:s');
				$model->save();
			}
		}
		
		return $this->redirect(['/user/update']);
	}
	
	public function actionDeletePhoto()
	{
		$model = $this->findModel(Yii::$app->getUser()->getId());
		
		if(!empty($model->photo)) {
			$pathToFile = $model->getPhotoPath();
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
			$model->photo = null;
			$model->updated_at = date('Y-m-d H:m:s');
			if (!$model->save()) {
				var_dump($model->errors);
			}
		}
		
		return $this->redirect(['/user/update']);
	}
	
	public function actionUpdateCover()
	{
		$model = $this->findModel(Yii::$app->getUser()->getId());
		
		$modelForm = new LoadCoverForm();
		$coverPost = Yii::$app->request->post();
		if ($modelForm->load($coverPost)) {
			if (!empty($model->cover)) {
				$pathToFile = $model->getCoverPath();
				if (file_exists($pathToFile)) {
					unlink($pathToFile);
				}
				$model->cover = null;
				$model->save();
			}
			if($modelForm->uploadMediaFile()) {
				$model->cover = $modelForm->cover;
				$model->updated_at = date('Y-m-d H:m:s');
				$model->save();
			}
		}
		
		return $this->redirect(['/user/update']);
	}
	
	public function actionDeleteCover()
	{
		$model = $this->findModel(Yii::$app->getUser()->getId());
		
		if(!empty($model->cover)) {
			$pathToFile = $model->getCoverPath();
			if (file_exists($pathToFile)) {
				unlink($pathToFile);
			}
			$model->cover = null;
			$model->updated_at = date('Y-m-d H:m:s');
			if (!$model->save()) {
				var_dump($model->errors);
			}
		}
		
		return $this->redirect(['/user/update']);
	}
    
	public function actionChangeEmail()
	{
		$model = $this->findModel(Yii::$app->getUser()->getId());
		$modelForm = new ChangeEmailForm();
		$changeEmailService = new ChangeEmailService();
		if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
			$changeEmailService->changeEmail($model, $modelForm->email);
			$changeEmailService->sendEmailConfirm($model, $modelForm->email);
		}
		
		return $this->redirect(['/user/update']);
	}
	
	public function actionChangeEmailConfirm($token)
	{
		try{
			$changeEmailService = new ChangeEmailService();
			$changeEmailService->confirmation($token);
			Yii::$app->session->setFlash('success', 'You have successfully confirmed your email.');
		} catch (\Exception $e){
			Yii::$app->errorHandler->logException($e);
			Yii::$app->session->setFlash('error', $e->getMessage());
		}
		
		return $this->redirect(['/user/update']);
	}
	
    /**
     * Finds the UserModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/user/update.php
<?php

use app\models\ChangeEmailForm;
use kartik\date\DatePicker;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserModel */
/* @var $modelForm app\models\UserUpdateForm */
/* @var $loadCoverModelForm app\models\LoadCoverForm */
/* @var $loadPhotoModelForm app\models\LoadPhotoForm */
/* @var $changeEmailForm app\models\ChangeEmailForm */

$this->title = 'Update ' . $model->username;
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="cabinet">
	<div class="page__header" style="background-image: url('<?php echo !empty($model->cover) ? "/" . \app\models\UserModel::FILE_COVER . $model->cover : "/images/member-cover.jpg"; ?>')">
		<div class="page__wrapper cabinet__header">
			<div class="cabinet__avatar cabinet__avatar--on">
				<img src="<?php echo !empty($model->photo) ?"/" . \app\models\UserModel::FILE_PHOTO . $model->photo : "/images/user-avatar.png"; ?>" alt="">
				<div class="cabinet__avatar_edit">
					<i class="cera-icon cera-edit-2"></i>
				</div>
			</div>
			<div class="cabinet__user_info">
				<div class="cabinet__user_name"><?php echo $model->username; ?></div>
				<div class="cabinet__activity">Online</div>
			</div>
			<a href="<?php echo \yii\helpers\Url::toRoute(['/user/update']); ?>" class="btn cabinet__edit_image"><i class="cera-icon cera-edit-2"></i> Edit Cover Image</a>
		</div>
	</div>
	<nav class="cabinet__nav">
		<div class="page__wrapper">
			<ul>
				<li><a class="active" href="<?php echo \yii\helpers\Url::toRoute(['/user/view']); ?>">Profile</a></li>
			</ul>
		</div>
	</nav>

	<div class="cabinet__content">
		<div class="page__wrapper">
			<nav class="cabinet__info_nav">
				<ul class="">
					<li><a  href="<?php echo \yii\helpers\Url::toRoute(['/user/view']); ?>"><i class="cera-icon cera-user"></i> Main profile</a></li>
					<li><a class="active" href="<?php echo \yii\helpers\Url::toRoute(['/user/update']); ?>"><i class="cera-icon cera-edit-2"></i> Edit Profile</a></li>
					<li><a href="<?php echo \yii\helpers\Url::toRoute(['/user-social/index']); ?>"><i class="cera-icon cera-image"></i> Social Networks</a></li>
				</ul>
			</nav>
			<div class="cabinet__inner">
				<div class="user-model-form bg-white">
					<?php $form = ActiveForm::begin(); ?>
						<div class="row">
							<div class="col-lg-6">
								<?= $form->field($modelForm, 'username')->textInput(['maxlength' => true]) ?>
								<?= $form->field($modelForm, 'first_name')->textInput(['maxlength' => true]) ?>
								<?= $form->field($modelForm, 'last_name')->textInput(['maxlength' => true]) ?>
								<?= $form->field($modelForm, 'birthdate', ['inputOptions' => [
									'autocomplete' => 'off']])->widget(DatePicker::class, [
									'type' => DatePicker::TYPE_COMPONENT_PREPEND,
									'pluginOptions' => [
										'autoclose' => true,
										'format' => 'yyyy-mm-dd'
									]
								]) ?>
								<?= $form->field($modelForm, 'gender')->dropDownList(\app\models\UserModel::statusList()) ?>
							</div>
							<div class="col-lg-6">
								<?= $form->field($modelForm, 'oldPassword')->passwordInput(['maxlength' => true]) ?>
								<?= $form->field($modelForm, 'newPassword')->passwordInput(['maxlength' => true]) ?>
								<?= $form->field($modelForm, 'confirmPassword')->passwordInput(['maxlength' => true]) ?>
							</div>
						</div>
						<div class="btn-group">
							<?= Html::submitButton('Save', ['class' => 'btn btn-lg btn-primary']) ?>
						</div>
					<?php ActiveForm::end(); ?>
				</div>
				
				<div class="user-model-form bg-white mt-5">
					<div class="row">
						<div class="col-lg-6">
							<h2>Change email form</h2>
							<p>Your active email is <b><?php echo $model->email; ?></b></p>
							<?php $form = ActiveForm::begin(['action' => ['user/change-email'], 'options' => ['method' => 'post']]); ?>
							<?= $form->field($changeEmailForm, 'email')->textInput(['maxlength' => true]) ?>
							<div class="btn-group">
								<?= Html::submitButton('Change', ['class' => 'btn btn-lg btn-primary']) ?>
							</div>
							<?php ActiveForm::end(); ?>
						</div>
					</div>
				</div>
				
				<div class="user-model-form bg-white mt-5">
					<div class="row">
						<div class="col-lg-6">
							<?php if (empty($model->photo)) { ?>
								<h2 class="mb-5">Change Avatar</h2>
								<?php $loadPhotoForm = ActiveForm::begin(['action' => ['user/update-photo'], 'options' => ['method' => 'post']]); ?>
								
								<?= $loadPhotoForm->field($loadPhotoModelForm, 'photoFile')->widget(FileInput::class); ?>
								
								<?php ActiveForm::end(); ?>
							<?php }else{ ?>
								<a href="<?php echo Url::toRoute(['/user/delete-photo']); ?>" title="Delete"
								   aria-label="Delete" data-pjax="0" data-confirm="Are you sure you want to delete this item?"
								   class="btn btn-warning"
								   data-method="post">Delete User Photo</a>
							<?php }; ?>
						</div>
						<div class="col-lg-6">
							<?php
							if (empty($model->cover)) { ?>
								<h2 class="mb-5">Load Cover Image</h2>
								<?php $loadCoverForm = ActiveForm::begin(['action' => ['user/update-cover'], 'options' => ['method' => 'post']]); ?>
								
								<?= $loadCoverForm->field($loadCoverModelForm, 'coverFile')->widget(FileInput::class); ?>
								
								<?php ActiveForm::end(); ?>
							<?php }else{ ?>
								<a href="<?php echo Url::toRoute(['/user/delete-cover']); ?>" title="Delete"
								   aria-label="Delete" data-pjax="0" data-confirm="Are you sure you want to delete this item?"
								   class="btn btn-warning"
								   data-method="post">Delete User Cover</a>
							<?php }; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UserModel */

$this->title = $model->username;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>

<div class="cabinet">
	<div class="page__header" style="background-image: url('<?php echo !empty($model->cover) ? "/" . \app\models\UserModel::FILE_COVER . $model->cover : "/images/member-cover.jpg"; ?>')">
		<div class="page__wrapper cabinet__header">
			<div class="cabinet__avatar cabinet__avatar--on">
				<img src="<?php echo !empty($model->photo) ?"/" . \app\models\UserModel::FILE_PHOTO . $model->photo : "/images/user-avatar.png"; ?>" alt="">
				<a href="<?php echo \yii\helpers\Url::toRoute(['/user/update']); ?>" class="cabinet__avatar_edit">
					<i class="cera-icon cera-edit-2"></i>
				</a>
			</div>
			<div class="cabinet__user_info">
				<div class="cabinet__user_name"><?php echo $model->username; ?></div>
				<div class="cabinet__activity">Online</div>
			</div>
			<a href="<?php echo \yii\helpers\Url::toRoute(['/user/update']); ?>" class="btn cabinet__edit_image"><i class="cera-icon cera-edit-2"></i> Edit Cover Image</a>
		</div>
	</div>
	<nav class="cabinet__nav">
		<div class="page__wrapper">
			<ul>
				<li><a class="active" href="<?php echo \yii\helpers\Url::toRoute(['/user/view']); ?>">Profile</a></li>
			</ul>
		</div>
	</nav>

	<div class="cabinet__content">
		<div class="page__wrapper">
			<nav class="cabinet__info_nav">
				<ul class="">
					<li><a class="active" href="<?php echo \yii\helpers\Url::toRoute(['/user/view']); ?>"><i class="cera-icon cera-user"></i> Main profile</a></li>
					<li><a href="<?php echo \yii\helpers\Url::toRoute(['/user/update']); ?>"><i class="cera-icon cera-edit-2"></i> Edit Profile</a></li>
					<li><a href="<?php echo \yii\helpers\Url::toRoute(['/user-social/index']); ?>"><i class="cera-icon cera-image"></i> Social Networks</a></li>
				</ul>
			</nav>
			<div class="cabinet__inner">
				<div class="cabinet__table">
					<div class="cabinet__table_row">
						<div class="cabinet__table_item">Name</div>
						<div class="cabinet__table_item"><?php echo $model->username; ?></div>
					</div>
					<div class="cabinet__table_row">
						<div class="cabinet__table_item">First Name</div>
						<div class="cabinet__table_item"><?php echo $model->first_name; ?></div>
					</div>
					<div class="cabinet__table_row">
						<div class="cabinet__table_item">Last Name</div>
						<div class="cabinet__table_item"><?php echo $model->last_name; ?></div>
					</div>
					<div class="cabinet__table_row">
						<div class="cabinet__table_item">email</div>
						<div class="cabinet__table_item"><?php echo $model->email; ?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>