controllers/UserSocialController.php
<?php

namespace app\controllers;

use app\models\Post;
use app\models\UserModel;
use Yii;
use app\models\Socials;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SocialController implements the CRUD actions for Socials model.
 */
class UserSocialController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'DetachSocial' => ['POST'],
                    'AttachSocial' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Socials models.
     * @return mixed
     */
    public function actionIndex()
    {
		$otherSocials = Socials::findOther(Yii::$app->getUser()->getId());
		$userSocials = Socials::findByUser(Yii::$app->getUser()->getId());
		
        return $this->render('index', [
        	'otherSocials' => $otherSocials,
        	'userSocials' => $userSocials,
		]);
    }
    
    public function actionAttachSocial($id)
    {
		if (!$social = Socials::findOne($id)) {
			throw new NotFoundHttpException('Social is not exist.');
		}
		
		$user = UserModel::findOne(['id' => Yii::$app->getUser()->getId()]);
		
        if ($user->isHasSocial($id)) {
			throw new NotFoundHttpException('Social is attached.');
        }
	
		$user->link('socials', $social);
        
        Yii::$app->session->setFlash('success', "Attached social " . $social->name . ' is successful.');
        
        return $this->redirect('/user-social/index');
    }
    
    public function actionDetachSocial($id)
    {
		if (!$social = Socials::findOne($id)) {
			throw new NotFoundHttpException('Social is not exist.');
		}
		
		$user = UserModel::findOne(['id' => Yii::$app->getUser()->getId()]);
		
        if (!$user->isHasSocial($id)) {
			throw new NotFoundHttpException('Social is detached.');
        }
        
		$posts = Post::findByUserAndSocial($user->id, $id);
        if (!empty($posts)) {
        	/** @var Post $post */
        	foreach ($posts as $post) {
				$post->unlink('socials', $social, true);
        	}
        }
  
		$user->unlink('socials', $social, true);
	
		Yii::$app->session->setFlash('success', "Detach social " . $social->name . ' is successful.');
        
        return $this->redirect('/user-social/index');
    }
}

views/user-social/index.php
<?php

/**
 * @var $otherSocials \app\models\Socials[]
 * @var $userSocials \app\models\Socials[]
 */

use yii\helpers\Url;

?>

<div class="page">
	<div class="page__wrapper py-5">
		<h4 class="page__subtitle">Connected Socials</h4>
		<div class="socials">
			<h3 class="block__title">Connected Socials</h3>
			<div class="socials__connected">
				<?php
				/** @var \app\models\Socials $userSocial */
				foreach ($userSocials as $userSocial) { ?>
					<?php if(empty( $userSocial->logo)) {?>
						<a class="fa fa-<?php echo $userSocial->name; ?> socials__item" href="<?php echo Url::toRoute(['/user-social/detach-social', 'id' => $userSocial->id]); ?>" data-method="post"></a>
					<?php } else { ?>
						<a class="socials__item" href="<?php echo Url::toRoute(['/user-social/detach-social', 'id' => $userSocial->id]); ?>" data-method="post">
							<img src="/<?= \app\models\Socials::FILE_PATH . $userSocial->logo ?>">
						</a>
					<?php }; ?>
				<?php }; ?>
			</div>
			<hr>
			<h3 class="block__title">You may connect other socials</h3>
			<div class="socials__disconnected">
				<?php
				/** @var \app\models\Socials $otherSocial */
				foreach ($otherSocials as $otherSocial) { ?>
					<?php if(empty( $otherSocial->logo)) {?>
						<a class="fa fa-<?php echo $otherSocial->name; ?> socials__item"
						href="<?php echo Url::toRoute(['/user-social/attach-social', 'id' => $otherSocial->id]); ?>"
						data-method="post"></a>
					<?php } else { ?>
						<a class="socials__item" href="<?php echo Url::toRoute(['/user-social/attach-social', 'id' => $otherSocial->id]); ?>" data-method="post">
							<img src="/<?= \app\models\Socials::FILE_PATH . $otherSocial->logo ?>">
						</a>
					<?php }; ?>
					
				<?php }; ?>
			</div>
		</div>
	</div>
</div>